### PR TITLE
fix(eventually-postgres): use global serial offset for sequence_number

### PR DESCRIPTION
**Pull request by to266**
Hello there :smiley: 

Recently, when inserting many aggregates into a repository (done via `AggregateRoot`s), we had a repeated `sequence_number` in the `events` table:

```sql
database=> select aggregate_id, aggregate_type, version, sequence_number, event->'type' as event_type from events where sequence_number=861;
             aggregate_id             |   aggregate_type   | version | sequence_number | event_type
--------------------------------------+--------------------+---------+-----------------+------------
 7e7704b6-175c-4186-b4ee-3f33ec2f6cd4 | my-type            |       1 |             861 | "Created"
 60742538-8de2-4428-9499-63c74a8990a6 | my-type            |       1 |             861 | "Created"
```
This unfortunately breaks the projections, as they normally are idempotent and ignore any events equal or earlier than the last processed one. This clearly means that only one of the above events will get processed -> not nice.

The PR fixes the issue (but I'm pretty sure that's not the only possible fix)

As a side-effect it adds a global counter to the events, so that they have an absolute order, whichever aggregate they come from. This sort-of happened before, but only per-aggregate-type, which made some other debugging things more difficult as well

### CODE REVIEW

**Comment by ar3s3ru** [comment]
Oww thank you so much for the PR! ❤️ 

Yes, using `BIGINT` was not a great idea for the `sequence_number`: ideally I would've used a `SERIAL`, but `tokio-postgres` was complaining when performing type deserialization (which is bad, I shouldn't have forced a SQL table design because of Rust library shortcomings...)

This should solve it, although I'm not sure if there might be some issue with projections 👀  (AFAIR, projections/subscriptions were expecting consecutive sequence numbers)

Have you had any issues with "gaps" in `sequence_number` values on the `events` table?

---

(Note: the implementation in [`eventually-go` uses `SERIAL` already](https://github.com/eventually-rs/eventually-go/blob/6c0eb0e0be7a540305ce99e05608feb1ecb95e3b/eventstore/postgres/migrations/1_create_stream_tables.up.sql#L10), and gave no issues at all, so your fix is supposed to work pretty fine 🎉 )

**Comment by to266** [comment]
Nope, no gaps yet. Also I don't think gaps **would** be an issue. It might "hint" at missed events on first sight, however it does not mean that afaik. As long as there are no repeated sequence numbers **and** it's monotonically increasing, all should be fine :)

---

As for projections/subscriptions: yes exactly, they were expecting consecutive sequence numbers. If a repeated one arrived, it was assumed that it's a duplicate (for example when first reading from eventstore itself and only then looking at the subscriber stream) and was ignored. 

Without the PR it would occasionally happen that the same sequence number got assigned to two actually distinct events that even belong to different aggregates -> and that lead to the second of the two events getting ignored, screwing up the projection.

Even worse, the projection would never fix itself, as the number will always be wrong, therefore always ignoring the second passed event (I did not check whether they always get returned in the same order, but it does not really matter either)

**Comment by ar3s3ru** [comment]
>As long as there are no repeated sequence numbers and it's monotonically increasing, all should be fine :)

Exactly, since the sequence number is monotonically increasing, and the event store is supposed to return an ordered stream, then gaps should be fine. However...

>As for projections/subscriptions: yes exactly, they were expecting consecutive sequence numbers.

...this might be a problem (I mean, the fact of requiring consecutive sequence numbers, not monotonically increasing ones, which is a more relaxed constraint). It seems as though I removed that constraint 😄 

https://github.com/eventually-rs/eventually-rs/blob/fcf705ef3e2f72bbeae61d6b75b6a67bcae6bf82/eventually-core/src/subscription.rs#L229-L234

>Nope, no gaps yet.

Out of paranoia, I would test this case though 👀 
Wouldn't want you having surprises in production 😅 

---

We can merge the PR but I think I need to patch some dependencies in current `master` (the CI is failing due to `eventually-app-example` and me not pinning exact crate version 😢)

Would you mind if I rebase on `master` once I do that?

**Comment by to266** [comment]
My bad, projections expect monotonically increasing sequence numbers too as far as I can tell.

And yes, feel free to rebase etc :+1:

**Comment by to266** [comment]
FYI added another commit that fixes related and very annoying bug. More info in the commit message

**Comment by ar3s3ru** [comment]
Hello @to266,

I've rebased to latest master and renamed the PR title to conform to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). Hope that's ok with you 😄 

Thank you again for your contribution ❤️

**Pull request merged**
